[package]
name = "brave_proton"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3", features = ["env"] }
env_logger = "0.9.0"
log = "0.4"
