[package]
name = "BraveProton"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "braveProton"
path = "src/main.rs"

[dependencies]
clap = "2.33"
cloudflare = "0.9.1"
maplit = "1"
serde = { version = "1.0" }
serde_json = "1"